# Gene copy number feature extraction

We adopted the differences in gene expression between genes within and outside specific pathways to characterize the gene expression features of cell lines. The Mann–Whitney U test is a non-parametric method used to determine whether two independent samples originate from the same continuous distribution. Its fundamental principle involves comparing the ranks of observations between the two samples to assess whether the locations of the population distributions differ [75]. Consequently, we employed this test to compute the differences in gene expression between genes within and outside gene sets. We utilized the c2_kegg_medicus canonical pathway collection comprising 619 gene sets, ultimately constructing 619 pathway difference features for each cell line sample. The specific construction method is as follows:

In [ ]:
import pandas as pd
from scipy import stats

In [2]:
def remove_brackets(x):
    return x.split('(')[0].strip()

In [3]:
df_exp = pd.read_csv('/kaggle/input/ccle-geneexp/OmicsExpressionProteinCodingGenesTPMLogp1-23Q2.csv')
df_exp.columns = df_exp.columns.map(remove_brackets)
df_exp.head(5)

,Unnamed: 0,TSPAN6,TNMD,DPM1,SCYL3,C1orf112,FGR,CFH,FUCA2,GCLC,...,H3C2,H3C3,AC098582.1,DUS4L-BCAP29,C8orf44-SGK3,ELOA3B,NPBWR1,ELOA3D,ELOA3,CDR1
0,ACH-001113,4.331992,0.000000,7.364660,2.792855,4.471187,0.028569,1.226509,3.044394,6.500005,...,2.689299,0.189034,0.201634,2.130931,0.555816,0.0,0.275007,0.0,0.0,0.000000
1,ACH-001289,4.567424,0.584963,7.106641,2.543496,3.504620,0.000000,0.189034,3.813525,4.221877,...,1.286881,1.049631,0.321928,1.464668,0.632268,0.0,0.014355,0.0,0.0,0.000000
2,ACH-001339,3.150560,0.000000,7.379118,2.333424,4.228049,0.056584,1.310340,6.687201,3.682573,...,0.594549,1.097611,0.831877,2.946731,0.475085,0.0,0.084064,0.0,0.0,0.042644
3,ACH-001538,5.085340,0.000000,7.154211,2.545968,3.084064,0.000000,5.868390,6.165309,4.489928,...,0.214125,0.632268,0.298658,1.641546,0.443607,0.0,0.028569,0.0,0.0,0.000000
4,ACH-000242,6.729417,0.000000,6.537917,2.456806,3.867896,0.799087,7.208478,5.570159,7.127117,...,1.117695,2.358959,0.084064,1.910733,0.000000,0.0,0.464668,0.0,0.0,0.000000

In [4]:
df_geneSet = pd.read_csv('/kaggle/input/c2-cp-geneset/c2.cp.kegg_legacy.v2023.2.Hs.symbols.csv', sep='\t',header=None)
df_geneSet.head(5)

                                                   0
0  KEGG_ABC_TRANSPORTERS,ABCA1,ABCA10,ABCA12,ABCA...
1  KEGG_ACUTE_MYELOID_LEUKEMIA,AKT1,AKT2,AKT3,ARA...
2  KEGG_ADHERENS_JUNCTION,ACP1,ACTB,ACTG1,ACTN1,A...
3  KEGG_ADIPOCYTOKINE_SIGNALING_PATHWAY,ACACB,ACS...
4  KEGG_ALANINE_ASPARTATE_AND_GLUTAMATE_METABOLIS...

In [5]:
# Retrieve all genes.
CCLEgeneSets = set(df_exp.columns.values[1:])
# Retrieve the name of the cell line.
cell_line_names = df_exp.iloc[0:,0]

In [6]:
U_test_result = []
pathways = []
# temp_ANOVA_counts = []
count = 0
for data in df_geneSet.values:
    geneSet_pathway = data[0].split(',')
    pathway,genes = geneSet_pathway[0],set(geneSet_pathway[1:])
    print(count+1,pathway)
    internal_genes = CCLEgeneSets & genes
    external_genes = CCLEgeneSets - internal_genes

    # Summarize the pathway data.
    pathways.append(pathway)

    # Internal data of the gene set.
    internal = df_exp[list(internal_genes)]
    # External data of the gene set.
    external = df_exp[list(external_genes)]

    
    U_stats = []
    
    for inter_data,exter_data in zip(internal.values,external.values):

        # Mann-Whitney U Test
        U_stat, p_value = stats.mannwhitneyu(inter_data.flatten(), exter_data.flatten(), alternative='two-sided')

        U_stats.append(p_value)

        # Check if there is a significant difference in variance.
        # F,p = stats.f_oneway(inter_data.flatten(), exter_data.flatten())
        # if p < 0.05:
        #     count+=1
    # print(count)
    count+=1
    U_test_result.append(U_stats)

1 KEGG_ABC_TRANSPORTERS
2 KEGG_ACUTE_MYELOID_LEUKEMIA
3 KEGG_ADHERENS_JUNCTION
4 KEGG_ADIPOCYTOKINE_SIGNALING_PATHWAY
5 KEGG_ALANINE_ASPARTATE_AND_GLUTAMATE_METABOLISM
6 KEGG_ALDOSTERONE_REGULATED_SODIUM_REABSORPTION
7 KEGG_ALLOGRAFT_REJECTION
8 KEGG_ALPHA_LINOLENIC_ACID_METABOLISM
9 KEGG_ALZHEIMERS_DISEASE
10 KEGG_AMINOACYL_TRNA_BIOSYNTHESIS
11 KEGG_AMINO_SUGAR_AND_NUCLEOTIDE_SUGAR_METABOLISM
12 KEGG_AMYOTROPHIC_LATERAL_SCLEROSIS_ALS
13 KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION
14 KEGG_APOPTOSIS
15 KEGG_ARACHIDONIC_ACID_METABOLISM
16 KEGG_ARGININE_AND_PROLINE_METABOLISM
17 KEGG_ARRHYTHMOGENIC_RIGHT_VENTRICULAR_CARDIOMYOPATHY_ARVC
18 KEGG_ASCORBATE_AND_ALDARATE_METABOLISM
19 KEGG_ASTHMA
20 KEGG_AUTOIMMUNE_THYROID_DISEASE
21 KEGG_AXON_GUIDANCE
22 KEGG_BASAL_CELL_CARCINOMA
23 KEGG_BASAL_TRANSCRIPTION_FACTORS
24 KEGG_BASE_EXCISION_REPAIR
25 KEGG_BETA_ALANINE_METABOLISM
26 KEGG_BIOSYNTHESIS_OF_UNSATURATED_FATTY_ACIDS
27 KEGG_BLADDER_CANCER
28 KEGG_BUTANOATE_METABOLISM
29 KEGG_B_CELL_RECEPTOR_SIGNALING_PATHWAY
30 KEGG_CALCIUM_SIGNALING_PATHWAY
31 KEGG_CARDIAC_MUSCLE_CONTRACTION
32 KEGG_CELL_ADHESION_MOLECULES_CAMS
33 KEGG_CELL_CYCLE
34 KEGG_CHEMOKINE_SIGNALING_PATHWAY
35 KEGG_CHRONIC_MYELOID_LEUKEMIA
36 KEGG_CIRCADIAN_RHYTHM_MAMMAL
37 KEGG_CITRATE_CYCLE_TCA_CYCLE
38 KEGG_COLORECTAL_CANCER
39 KEGG_COMPLEMENT_AND_COAGULATION_CASCADES
40 KEGG_CYSTEINE_AND_METHIONINE_METABOLISM
41 KEGG_CYTOKINE_CYTOKINE_RECEPTOR_INTERACTION
42 KEGG_CYTOSOLIC_DNA_SENSING_PATHWAY
43 KEGG_DILATED_CARDIOMYOPATHY
44 KEGG_DNA_REPLICATION
45 KEGG_DORSO_VENTRAL_AXIS_FORMATION
46 KEGG_DRUG_METABOLISM_CYTOCHROME_P450
47 KEGG_DRUG_METABOLISM_OTHER_ENZYMES
48 KEGG_ECM_RECEPTOR_INTERACTION
49 KEGG_ENDOCYTOSIS
50 KEGG_ENDOMETRIAL_CANCER
51 KEGG_EPITHELIAL_CELL_SIGNALING_IN_HELICOBACTER_PYLORI_INFECTION
52 KEGG_ERBB_SIGNALING_PATHWAY
53 KEGG_ETHER_LIPID_METABOLISM
54 KEGG_FATTY_ACID_METABOLISM
55 KEGG_FC_EPSILON_RI_SIGNALING_PATHWAY
56 KEGG_FC_GAMMA_R_MEDIATED_PHAGOCYTOSIS
57 KEGG_FOCAL_ADHESION
58 KEGG_FOLATE_BIOSYNTHESIS
59 KEGG_FRUCTOSE_AND_MANNOSE_METABOLISM
60 KEGG_GALACTOSE_METABOLISM
61 KEGG_GAP_JUNCTION
62 KEGG_GLIOMA
63 KEGG_GLUTATHIONE_METABOLISM
64 KEGG_GLYCEROLIPID_METABOLISM
65 KEGG_GLYCEROPHOSPHOLIPID_METABOLISM
66 KEGG_GLYCINE_SERINE_AND_THREONINE_METABOLISM
67 KEGG_GLYCOLYSIS_GLUCONEOGENESIS
68 KEGG_GLYCOSAMINOGLYCAN_BIOSYNTHESIS_CHONDROITIN_SULFATE
69 KEGG_GLYCOSAMINOGLYCAN_BIOSYNTHESIS_HEPARAN_SULFATE
70 KEGG_GLYCOSAMINOGLYCAN_BIOSYNTHESIS_KERATAN_SULFATE
71 KEGG_GLYCOSAMINOGLYCAN_DEGRADATION
72 KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_GANGLIO_SERIES
73 KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_GLOBO_SERIES
74 KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_LACTO_AND_NEOLACTO_SERIES
75 KEGG_GLYCOSYLPHOSPHATIDYLINOSITOL_GPI_ANCHOR_BIOSYNTHESIS
76 KEGG_GLYOXYLATE_AND_DICARBOXYLATE_METABOLISM
77 KEGG_GNRH_SIGNALING_PATHWAY
78 KEGG_GRAFT_VERSUS_HOST_DISEASE
79 KEGG_HEDGEHOG_SIGNALING_PATHWAY
80 KEGG_HEMATOPOIETIC_CELL_LINEAGE
81 KEGG_HISTIDINE_METABOLISM
82 KEGG_HOMOLOGOUS_RECOMBINATION
83 KEGG_HUNTINGTONS_DISEASE
84 KEGG_HYPERTROPHIC_CARDIOMYOPATHY_HCM
85 KEGG_INOSITOL_PHOSPHATE_METABOLISM
86 KEGG_INSULIN_SIGNALING_PATHWAY
87 KEGG_INTESTINAL_IMMUNE_NETWORK_FOR_IGA_PRODUCTION
88 KEGG_JAK_STAT_SIGNALING_PATHWAY
89 KEGG_LEISHMANIA_INFECTION
90 KEGG_LEUKOCYTE_TRANSENDOTHELIAL_MIGRATION
91 KEGG_LIMONENE_AND_PINENE_DEGRADATION
92 KEGG_LINOLEIC_ACID_METABOLISM
93 KEGG_LONG_TERM_DEPRESSION
94 KEGG_LONG_TERM_POTENTIATION
95 KEGG_LYSINE_DEGRADATION
96 KEGG_LYSOSOME
97 KEGG_MAPK_SIGNALING_PATHWAY
98 KEGG_MATURITY_ONSET_DIABETES_OF_THE_YOUNG
99 KEGG_MELANOGENESIS
100 KEGG_MELANOMA
101 KEGG_METABOLISM_OF_XENOBIOTICS_BY_CYTOCHROME_P450
102 KEGG_MISMATCH_REPAIR
103 KEGG_MTOR_SIGNALING_PATHWAY
104 KEGG_NATURAL_KILLER_CELL_MEDIATED_CYTOTOXICITY
105 KEGG_NEUROACTIVE_LIGAND_RECEPTOR_INTERACTION
106 KEGG_NEUROTROPHIN_SIGNALING_PATHWAY
107 KEGG_NICOTINATE_AND_NICOTINAMIDE_METABOLISM
108 KEGG_NITROGEN_METABOLISM
109 KEGG_NOD_LIKE_RECEPTOR_SIGNALING_PATHWAY
110 KEGG_NON_HOMOLOGOUS_END_JOINING
111 KEGG_NON_SMALL_CELL_LUNG_CANCER
112 KEGG_NOTCH_SIGNALING_PATHWAY
113 KEGG_NUCLEOTIDE_EXCISION_REPAIR
114 KEGG_N_GLYCAN_BIOSYNTHESIS
115 KEGG_OLFACTORY_TRANSDUCTION
116 KEGG_ONE_CARBON_POOL_BY_FOLATE
117 KEGG_OOCYTE_MEIOSIS
118 KEGG_OTHER_GLYCAN_DEGRADATION
119 KEGG_OXIDATIVE_PHOSPHORYLATION
120 KEGG_O_GLYCAN_BIOSYNTHESIS
121 KEGG_P53_SIGNALING_PATHWAY
122 KEGG_PANCREATIC_CANCER
123 KEGG_PANTOTHENATE_AND_COA_BIOSYNTHESIS
124 KEGG_PARKINSONS_DISEASE
125 KEGG_PATHOGENIC_ESCHERICHIA_COLI_INFECTION
126 KEGG_PATHWAYS_IN_CANCER
127 KEGG_PENTOSE_AND_GLUCURONATE_INTERCONVERSIONS
128 KEGG_PENTOSE_PHOSPHATE_PATHWAY
129 KEGG_PEROXISOME
130 KEGG_PHENYLALANINE_METABOLISM
131 KEGG_PHOSPHATIDYLINOSITOL_SIGNALING_SYSTEM
132 KEGG_PORPHYRIN_AND_CHLOROPHYLL_METABOLISM
133 KEGG_PPAR_SIGNALING_PATHWAY
134 KEGG_PRIMARY_BILE_ACID_BIOSYNTHESIS
135 KEGG_PRIMARY_IMMUNODEFICIENCY
136 KEGG_PRION_DISEASES
137 KEGG_PROGESTERONE_MEDIATED_OOCYTE_MATURATION
138 KEGG_PROPANOATE_METABOLISM
139 KEGG_PROSTATE_CANCER
140 KEGG_PROTEASOME
141 KEGG_PROTEIN_EXPORT
142 KEGG_PROXIMAL_TUBULE_BICARBONATE_RECLAMATION
143 KEGG_PURINE_METABOLISM
144 KEGG_PYRIMIDINE_METABOLISM
145 KEGG_PYRUVATE_METABOLISM
146 KEGG_REGULATION_OF_ACTIN_CYTOSKELETON
147 KEGG_REGULATION_OF_AUTOPHAGY
148 KEGG_RENAL_CELL_CARCINOMA
149 KEGG_RENIN_ANGIOTENSIN_SYSTEM
150 KEGG_RETINOL_METABOLISM
151 KEGG_RIBOFLAVIN_METABOLISM
152 KEGG_RIBOSOME
153 KEGG_RIG_I_LIKE_RECEPTOR_SIGNALING_PATHWAY
154 KEGG_RNA_DEGRADATION
155 KEGG_RNA_POLYMERASE
156 KEGG_SELENOAMINO_ACID_METABOLISM
157 KEGG_SMALL_CELL_LUNG_CANCER
158 KEGG_SNARE_INTERACTIONS_IN_VESICULAR_TRANSPORT
159 KEGG_SPHINGOLIPID_METABOLISM
160 KEGG_SPLICEOSOME
161 KEGG_STARCH_AND_SUCROSE_METABOLISM
162 KEGG_STEROID_BIOSYNTHESIS
163 KEGG_STEROID_HORMONE_BIOSYNTHESIS
164 KEGG_SULFUR_METABOLISM
165 KEGG_SYSTEMIC_LUPUS_ERYTHEMATOSUS
166 KEGG_TASTE_TRANSDUCTION
167 KEGG_TAURINE_AND_HYPOTAURINE_METABOLISM
168 KEGG_TERPENOID_BACKBONE_BIOSYNTHESIS
169 KEGG_TGF_BETA_SIGNALING_PATHWAY
170 KEGG_THYROID_CANCER
171 KEGG_TIGHT_JUNCTION
172 KEGG_TOLL_LIKE_RECEPTOR_SIGNALING_PATHWAY
173 KEGG_TRYPTOPHAN_METABOLISM
174 KEGG_TYPE_II_DIABETES_MELLITUS
175 KEGG_TYPE_I_DIABETES_MELLITUS
176 KEGG_TYROSINE_METABOLISM
177 KEGG_T_CELL_RECEPTOR_SIGNALING_PATHWAY
178 KEGG_UBIQUITIN_MEDIATED_PROTEOLYSIS
179 KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_BIOSYNTHESIS
180 KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_DEGRADATION
181 KEGG_VASCULAR_SMOOTH_MUSCLE_CONTRACTION
182 KEGG_VASOPRESSIN_REGULATED_WATER_REABSORPTION
183 KEGG_VEGF_SIGNALING_PATHWAY
184 KEGG_VIBRIO_CHOLERAE_INFECTION
185 KEGG_VIRAL_MYOCARDITIS
186 KEGG_WNT_SIGNALING_PATHWAY

In [7]:
# row: pathway; column: cell line name.
GeneExp_T_test_Analysis = pd.DataFrame(U_test_result,index=pathways,
                                                   columns=cell_line_names)

In [8]:
GeneExp_T_test_Analysis.to_csv("GeneExp_Wilcoxon_test_Analysis_U_stats_C2_KEGG186.csv")